# Generated by Django 6.1.1 on 2026-09-25 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Realisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=35)),
                ('description', models.TextField()),
                ('photo_principale', models.ImageField(upload_to='media/project')),
                ('date_realisation', models.DateField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.services')),
            ],
        ),
        migrations.CreateModel(
            name='RealisationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='media/project')),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realisation.realisation')),
            ],
        ),
    ]
