# Generated by Django 6.1.1 on 2026-09-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avis',
            name='est_valide',
            field=models.BooleanField(default=True, help_text='Cocher pour publier cet avis sur le site'),
        ),
    ]
